sgd/reproduction/playground/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>削除市区郡町名・番地</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PostNumber__c</fullName>
        <label>削除郵便番号</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pref__c</fullName>
        <label>削除都道府県</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>AccountType</fullName>
        <active>true</active>
        <description>取引のある得意先</description>
        <label>得意先</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

sgd/reproduction/playground/classes/pcLeadGetAccountInfoTEST.cls
@isTest
private class pcLeadGetAccountInfoTEST
{
    @isTest
    static void runTest()
    {
        Id RecordTypeId = [SELECT id FROM RecordType WHERE DeveloperName = 'AccountType' LIMIT 1].Id;
        Account Acc = new Account(Name = 'test', PostNumber__c = '1111111', Pref__c = 'test', Address__c = 'test', RecordTypeId = RecordTypeId);
        
        Database.SaveResult resultAcc = Database.insert(Acc , false);
        Id AccId = resultAcc.getId();
        
        Lead oLead = new Lead( LastName = '姓', AccountID_ForMA__c = AccId , Company = AccId);
        insert oLead ;
    }
}