sgd/reproduction/playground/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SMAX_PS_LastName__c</fullName>
        <label>姓</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Segment__c</fullName>
        <label>セグメント</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
        <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
        <label>Component SN</label>
        <referenceTo>SVMXC__Installed_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Case1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the product for which customer is seeking support. Reference to Product2 object.</description>
        <inlineHelpText>Choose or enter the Product name for which the customer is seeking support.</inlineHelpText>
        <label>Component Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
        <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
        <label>Site</label>
        <referenceTo>SVMXC__Site__c</referenceTo>
        <relationshipLabel>Cases Reported From This Site</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Case_Line__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Case Line</description>
    <fields>
        <fullName>SVMXC__Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Lines</relationshipLabel>
        <relationshipName>Case_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SVMXC__Installed_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an existing installed product record</description>
        <label>Installed Product</label>
        <referenceTo>SVMXC__Installed_Product__c</referenceTo>
        <relationshipLabel>Case Lines</relationshipLabel>
        <relationshipName>Case_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an existing product record</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Lines</relationshipLabel>
        <relationshipName>Case_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Installed_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <fields>
        <fullName>SMAX_PS_Segment__c</fullName>
        <label>セグメント</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
        <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N70000001hzZ0EAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
        <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>R00N70000001hzchEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current physical location of the product. This is a lookup to an existing location record</description>
        <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
        <label>Location</label>
        <referenceTo>SVMXC__Site__c</referenceTo>
        <relationshipName>R00N70000001hzcqEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Quote__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>In ServiceMax, Quote contains the estimated cost of a service event to be presented to a customer to get approval. A quote can be either created manually or generated automatically from the estimate lines of a service order.</description>
    <fields>
        <fullName>SMAX_PS_Delivery_Condition__c</fullName>
        <label>引渡条件</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <label>サービス報告書のサインをもってお引渡しと致します</label>
                </value>
                <value>
                    <fullName>1002</fullName>
                    <label>作業報告書の発送をもってお引渡しと致します</label>
                </value>
                <value>
                    <fullName>1003</fullName>
                    <label>部品納品にてお引渡しと致します</label>
                </value>
                <value>
                    <fullName>1004</fullName>
                    <label>製品納入にてお引渡しと致します</label>
                </value>
                <value>
                    <fullName>9999</fullName>
                    <label>特殊</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_OutPut_Type__c</fullName>
        <label>帳票様式（HTS/HOR）</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_OutPutType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Segment__c</fullName>
        <label>セグメント</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer account for whom the quote is prepared. Is a lookup to an existing salesforce account record</description>
        <inlineHelpText>Customer account for whom the quote is prepared. Is a lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Service_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service order number for which this quote is created. Is a lookup to an existing service order record in ServiceMax</description>
        <inlineHelpText>Service order number for which this quote is created. Is a lookup to an existing service order record in ServiceMax</inlineHelpText>
        <label>Work Order</label>
        <referenceTo>SVMXC__Service_Order__c</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <fields>
        <fullName>SMAX_PS_Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Installed Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Segment__c</fullName>
        <label>セグメント</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス見積</label>
        <referenceTo>SVMXC__Quote__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
        <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
        <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
        <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
        <label>Component</label>
        <referenceTo>SVMXC__Installed_Product__c</referenceTo>
        <relationshipName>Service_Order_Component</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product in which specialization would be required to service the work order. Calculated from installed product by OptiMax pre-calculation engine</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>SVMXC__Site__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Site__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <fields>
        <fullName>SVMXC__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your account.</description>
        <inlineHelpText>The company to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your company</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/globalValueSets/SMAX_PS_OutPutType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HTS</fullName>
        <default>true</default>
        <label>HTS様式</label>
    </customValue>
    <customValue>
        <fullName>HOR</fullName>
        <label>HOR様式</label>
    </customValue>
    <masterLabel>帳票様式（HTS/HOR）</masterLabel>
</GlobalValueSet>

sgd/reproduction/playground/globalValueSets/SMAX_PS_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Automotive</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>P&amp;E</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Medical</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Semi</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Scientific</label>
    </customValue>
    <customValue>
        <fullName>X</fullName>
        <label>不明</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <isActive>false</isActive>
        <label>Common</label>
    </customValue>
    <masterLabel>セグメント</masterLabel>
</GlobalValueSet>

sgd/reproduction/playground/classes/SMAX_PS_SetFieldsOnWOWebServ_UT.cls
/**
* @CLASS: SMAX_PS_SetFieldsOnWOWebServ_UT
*
* @DESCRIPTION: This is the test class for SMAX_PS_SetFieldsOnWOWebServ
*
*-------------------------------------------------------------------------------------------------------------------
* DEVELOPER                     DATE                  REASON
*-------------------------------------------------------------------------------------------------------------------
* ServiceMax/Shreyas         2021-03-08              Created
********************************************************************************************************************/
@isTest(seeAllData = false)
private class SMAX_PS_SetFieldsOnWOWebServ_UT
{
    static testMethod void testSetAddress()
    {
        Account testAcc = new Account(
            Name = 'Test Account',
            BillingCity = 'Tokyo',
            BillingCountry = 'Japan',
            BillingState = 'Tokyo'
        );
        Insert testAcc;

        SVMXC__Service_Order__c testWO = new SVMXC__Service_Order__c(
            SVMXC__Company__c = testAcc.Id,
            SMAX_PS_Address_Type__c = 'Account'
        );
        Insert testWO;
        
        

        // SFM Request object
        SVMXC.SFM_WrapperDef.SFM_TargetRecord request = new SVMXC.SFM_WrapperDef.SFM_TargetRecord();

        // ***** HEADER OBJECT ********************************
        // SFM Header Record and associate to the SFM request
        SVMXC.SFM_WrapperDef.SFM_TargetRecordObject headerRecord = new SVMXC.SFM_WrapperDef.SFM_TargetRecordObject();
        headerRecord.objName = 'SVMXC__Service_Order__c';
        request.headerRecord = headerRecord;

        // SFM Records and associate to the SFM Header Record
        List<SVMXC.SFM_WrapperDef.SFM_Record> woRecords = new List<SVMXC.SFM_WrapperDef.SFM_Record>();
        headerRecord.records = woRecords;

        // SFM Record for the SFM Records in Header
        SVMXC.SFM_WrapperDef.SFM_Record woRecord = new SVMXC.SFM_WrapperDef.SFM_Record();
        woRecord.sourceRecordId = testWO.Id;
        woRecord.targetRecordId = testWO.Id;
        List<SVMXC.SFM_WrapperDef.SFM_StringMap> woRecordAsKeyValue = new List<SVMXC.SFM_WrapperDef.SFM_StringMap>();
        woRecordAsKeyValue.add(new SVMXC.SFM_WrapperDef.SFM_StringMap('Id', testWO.Id));
        
        woRecord.targetRecordAsKeyValue = woRecordAsKeyValue;
        woRecords.add(woRecord);

        SMAX_PS_SetFieldsOnWOWebServ.setAddressOnChange(request);
    }
    static testMethod void testSetIP()
    {
        Account testAcc = new Account(
            Name = 'Test Account',
            BillingCity = 'Tokyo',
            BillingCountry = 'Japan',
            BillingState = 'Tokyo'
        );
        Insert testAcc;
		Product2 product = new Product2(
            Name='Test Product'
        );
        Insert product;

        SVMXC__Site__c testLoc = SMAX_PS_TestDataFactory.CreateLocation('TestLoc');
        testLoc.SVMXC__Account__c=testAcc.Id;
        insert testLoc;
        
        SVMXC__Installed_Product__c testIP = new SVMXC__Installed_Product__c(
            Name = 'Test IP',
            SVMXC__Product__c = product.Id,
            SVMXC__Company__c = testAcc.Id,
            SVMXC__Site__c=testLoc.id
        );
        Insert testIP;
        Case testCase=new Case(
            AccountId=testAcc.Id,
            SMAX_PS_LastName__c='Test Name',
            SMAX_PS_Segment__c='1',
            SuppliedEmail='test@test.com'
            
        );
        Insert testCase;
        
        
        SVMXC__Case_Line__c testCaseLine = new SVMXC__Case_Line__c(
            SVMXC__Case__c=testCase.Id,
            SVMXC__Installed_Product__c = testIP.Id,
            SVMXC__Product__c = product.Id
            
        );
        Insert testCaseLine;
        
        SVMXC__Quote__c testQuote = new SVMXC__Quote__c(
            SVMXC__Company__c = testAcc.Id,
            SMAX_PS_OutPut_Type__c = 'HTS',
            SMAX_PS_Segment__c='1',
            SMAX_PS_Delivery_Condition__c = '1001'
            
        );
        Insert testQuote;
        

        SVMXC__Service_Order__c testWO = new SVMXC__Service_Order__c(
            SVMXC__Company__c = testAcc.Id,
            SMAX_PS_Address_Type__c = 'Account',
            SVMXC__Component__c = testIP.Id,
            SVMXC__Case__c = testCase.Id,
            SMAX_PS_Service_Quote__c = testQuote.Id
        );
        Insert testWO;

        // SFM Request object
        SVMXC.SFM_WrapperDef.SFM_TargetRecord request = new SVMXC.SFM_WrapperDef.SFM_TargetRecord();

        // ***** HEADER OBJECT ********************************
        // SFM Header Record and associate to the SFM request
        SVMXC.SFM_WrapperDef.SFM_TargetRecordObject headerRecord = new SVMXC.SFM_WrapperDef.SFM_TargetRecordObject();
        headerRecord.objName = 'SVMXC__Service_Order__c';
        request.headerRecord = headerRecord;

        // SFM Records and associate to the SFM Header Record
        List<SVMXC.SFM_WrapperDef.SFM_Record> woRecords = new List<SVMXC.SFM_WrapperDef.SFM_Record>();
        headerRecord.records = woRecords;

        // SFM Record for the SFM Records in Header
        SVMXC.SFM_WrapperDef.SFM_Record woRecord = new SVMXC.SFM_WrapperDef.SFM_Record();
        woRecord.sourceRecordId = testWO.Id;
        woRecord.targetRecordId = testWO.Id;
        List<SVMXC.SFM_WrapperDef.SFM_StringMap> woRecordAsKeyValue = new List<SVMXC.SFM_WrapperDef.SFM_StringMap>();
        woRecordAsKeyValue.add(new SVMXC.SFM_WrapperDef.SFM_StringMap('Id', testWO.Id));
        
        woRecord.targetRecordAsKeyValue = woRecordAsKeyValue;
        woRecords.add(woRecord);

        SMAX_PS_SetFieldsOnWOWebServ.setIPDataOnChange(request);
        SMAX_PS_SetFieldsOnWOWebServ.setFieldsOnLoad(request);
    }
}