sgd/reproduction/playground/objects/SMAX_PS_Quote_Lines__c.object
<CustomObject>
    <fields>
        <fullName>SMAX_PS_Customer_Procured__c</fullName>
        <defaultValue>false</defaultValue>
        <label>顧客支給品</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>品目</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Refer_PB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>価格表参照</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Quote_IP_Line__c</fullName>
        <label>見積対象製品・項番</label>
        <referenceTo>SMAX_PS_Service_Quote_IP_Line__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>見積明細</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SMAX_PS_Service_Quote_IP_Line__c.object
<CustomObject>
    <fields>
        <fullName>SMAX_PS_ClonedFromServiceQuoteIPLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>元見積対象製品・項番</label>
        <referenceTo>SMAX_PS_Service_Quote_IP_Line__c</referenceTo>
        <relationshipLabel>見積対象製品・項番</relationshipLabel>
        <relationshipName>Service_Quote_IP_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>製品</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Quote IP Line</relationshipLabel>
        <relationshipName>Service_Quote_IP_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>その他価格表</label>
        <referenceTo>SVMXC__Service_Pricebook__c</referenceTo>
        <relationshipLabel>Service Quote IP Line</relationshipLabel>
        <relationshipName>Service_Quote_IP_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>見積対象製品・項番</label>
    <nameField>
        <displayFormat>SIP-{0000000}</displayFormat>
        <label>Service Quote IP Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Activity_Master__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Activity Master definition is used to define the activity related to activity performed.</description>
    <label>Activity Master</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Activity_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Attach Activity Products Activity Product Level for the Activity Master.</description>
    <fields>
        <fullName>SVMXC__Activity_Product__c</fullName>
        <formula>TEXT(SVMXC__Activity__r.SVMXC__Activity_Type__c)+ &quot; : &quot; +
IF(LEN(SVMXC__Product__r.Id) &gt; 0,SVMXC__Product__r.Name,
IF(LEN(TEXT( SVMXC__Product_Line__c )) &gt; 0,TEXT(SVMXC__Product_Line__c),
IF(LEN(TEXT( SVMXC__Product_Family__c )) &gt; 0,TEXT(SVMXC__Product_Family__c),&apos;&apos;
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Activity Product</label>
        <type>Text</type>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Quote__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>In ServiceMax, Quote contains the estimated cost of a service event to be presented to a customer to get approval. A quote can be either created manually or generated automatically from the estimate lines of a service order.</description>
    <fields>
        <fullName>SMAX_PS_Delivery_Condition__c</fullName>
        <label>引渡条件</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <label>サービス報告書のサインをもってお引渡しと致します</label>
                </value>
                <value>
                    <fullName>1002</fullName>
                    <label>作業報告書の発送をもってお引渡しと致します</label>
                </value>
                <value>
                    <fullName>1003</fullName>
                    <label>部品納品にてお引渡しと致します</label>
                </value>
                <value>
                    <fullName>1004</fullName>
                    <label>製品納入にてお引渡しと致します</label>
                </value>
                <value>
                    <fullName>9999</fullName>
                    <label>特殊</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Parts_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>部品価格表</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Service_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス価格表</label>
        <referenceTo>SVMXC__Service_Pricebook__c</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Service_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Required_Part__c.object
<CustomObject>
    <description>Parts used to perform task</description>
    <label>Required Part</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Service_Pricebook__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Represents a price book that contains the list of services that your organization sells.</description>
    <label>Service Pricebook</label>
    <nameField>
        <label>Pricebook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Pricebooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Service_Pricebook_Entry__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Represent price entry for service</description>
    <fields>
        <fullName>SVMXC__Activity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Product</label>
        <referenceTo>SVMXC__Activity_Product__c</referenceTo>
        <relationshipLabel>Service Pricebook Entry</relationshipLabel>
        <relationshipName>Service_Pricebook_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Pricebook Entry</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Pricebook Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Task_Template__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>This object stores reusable task templates and a list of tasks, separated by record type. Task templates are used in preventive maintenance.</description>
    <fields>
        <fullName>SVMXC__Task_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Task Template.</description>
        <inlineHelpText>Select the Task Template.</inlineHelpText>
        <label>Work Order Purpose</label>
        <referenceTo>SVMXC__Task_Template__c</referenceTo>
        <relationshipLabel>Task Templates</relationshipLabel>
        <relationshipName>Task_templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task Template</label>
    <nameField>
        <displayFormat>TT-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/classes/SMAX_PS_ServiceQuotePricing_Test.cls
/**
* @description       : Test Data Class 
* @author            : Pavithira (SpringFive)
* @group             : Servicemax PS
* @last modified on  : 24-05-2021
* @last modified by  : Deepak Andeli
* Modifications Log 
* Ver   Date         Author                               Modification
* 1.0   10-22-2020   Pavithira                 Initial Version
**/
@isTest
public with sharing class SMAX_PS_ServiceQuotePricing_Test {

      static testMethod void createQuoteLineTest(){
          
        //Create product,tasktemplate,ActivityMaster and RequiredParts
        Product2 product = SMAX_PS_TestDataFactory.CreateProduct('Test Product','3000');
        insert product;
        SVMXC__Task_Template__c ttemplate = SMAX_PS_TestDataFactory.CreateTasktemplate('testTemplate');
        insert ttemplate;
        SVMXC__Activity_Master__c activityMaster = SMAX_PS_TestDataFactory.createActivityMaster('3000');
        insert activityMaster;
        SVMXC__Activity_Product__c activityProduct = SMAX_PS_TestDataFactory.createActivityProduct(activityMaster,product);
        insert activityProduct; 
        List<SVMXC__Required_Part__c> reqPartList = new List<SVMXC__Required_Part__c>();
        SVMXC__Required_Part__c requiredPart1 = SMAX_PS_TestDataFactory.createRequiredPart(ttemplate,null,activityMaster,'1001','3000');
        SVMXC__Required_Part__c requiredPart = SMAX_PS_TestDataFactory.createRequiredPart(ttemplate,null,activityMaster,'1002','4000');
        SVMXC__Required_Part__c requiredPart2 = SMAX_PS_TestDataFactory.createRequiredPart(ttemplate,product,null,'1003',null);
        reqPartList.add(requiredPart1);
        reqPartList.add(requiredPart);
        reqPartList.add(requiredPart2);
        insert reqPartList;
        
        //Create Pricing records
        PricebookEntry stdPriceBookEntry = new PricebookEntry();
        stdPriceBookEntry.Pricebook2Id = Test.getStandardPricebookId();
        stdPriceBookEntry.IsActive = True;
        stdPriceBookEntry.Product2Id = product.id;
        stdPriceBookEntry.UnitPrice = 100;
        insert stdPriceBookEntry;
        List<Pricebook2> priceBookList = new List<Pricebook2>();
        Pricebook2 pricebookFirst = SMAX_PS_TestDataFactory.CreatePricebook('Test Parts Pricebook1');
        Pricebook2 pricebookSecond = SMAX_PS_TestDataFactory.CreatePricebook('Test Parts Pricebook2');
        priceBookList.add(pricebookFirst);
        priceBookList.add(pricebookSecond);
        insert priceBookList;
        List<PricebookEntry> priceBookEntryList = new List<PricebookEntry>();
        PricebookEntry pbEntry1 = SMAX_PS_TestDataFactory.CreatePricebookentry(pricebookFirst,product,100);
        PricebookEntry pbEntry2 = SMAX_PS_TestDataFactory.CreatePricebookentry(pricebookSecond,product,200);
        priceBookEntryList.add(pbEntry1);
        priceBookEntryList.add(pbEntry2);
        insert priceBookEntryList;
        List<SVMXC__Service_Pricebook__c> servicePriceBookList = new List<SVMXC__Service_Pricebook__c>();
        SVMXC__Service_Pricebook__c spbookFirst = SMAX_PS_TestDataFactory.CreateServicePricebook('Test ServicePricebook1'); 
        SVMXC__Service_Pricebook__c spbookSecond = SMAX_PS_TestDataFactory.CreateServicePricebook('Test ServicePricebook2'); 
        servicePriceBookList.add(spbookFirst);
        servicePriceBookList.add(spbookSecond);
        insert servicePriceBookList;
        List<SVMXC__Service_Pricebook_Entry__c> servicePriceBookEntryList = new List<SVMXC__Service_Pricebook_Entry__c>();  
        SVMXC__Service_Pricebook_Entry__c spbookEntryFirst = SMAX_PS_TestDataFactory.CreateServicePricebookEntry(spbookFirst,activityProduct); 
        SVMXC__Service_Pricebook_Entry__c spbookEntrySecond = SMAX_PS_TestDataFactory.CreateServicePricebookEntry(spbookSecond,activityProduct);   
        servicePriceBookEntryList.add(spbookEntryFirst);
        servicePriceBookEntryList.add(spbookEntrySecond);  
        insert servicePriceBookEntryList;
          
        //Creating Account,Quote,QuoteIPLine for method "CreateQuoteLine"
        Account newAccount = SMAX_PS_TestDataFactory.CreateAccount('Test Account','state','city');
        insert newAccount;
        SVMXC__Quote__c serviceQuote = SMAX_PS_TestDataFactory.CreateServiceQuote(newAccount,pricebookFirst,spbookFirst,'testDeliveryCondition','HTS','draft');
        serviceQuote.SMAX_PS_Delivery_Condition__c='9999';
        insert serviceQuote;
        SMAX_PS_Service_Quote_IP_Line__c serviceQuoteIPLine = SMAX_PS_TestDataFactory.CreateServiceQuoteIpLines(serviceQuote,ttemplate);
        insert serviceQuoteIPLine;
        /***************Coverage for method "CreateQuoteLine" ends*****************/
        
        //Creating and updating quote lines for method "UpdateQuoteLinePriceBeforeInsertUpdate"
        SVMX_PS_ServiceQuotePricing.triggerfromQuote = true;
        List<SMAX_PS_Quote_Lines__c> qlList = new List<SMAX_PS_Quote_Lines__c>();
        Product2 productSecond = SMAX_PS_TestDataFactory.CreateProduct('Test Product','3000');
        insert productSecond;
        SMAX_PS_Quote_Lines__c quoteLine1 = SMAX_PS_TestDataFactory.CreateQuoteLines(serviceQuote,serviceQuoteIPLine,'1001',null);
        SMAX_PS_Quote_Lines__c quoteLine2 = SMAX_PS_TestDataFactory.CreateQuoteLines(serviceQuote,serviceQuoteIPLine,'1003',product);
        SMAX_PS_Quote_Lines__c quoteLine3 = SMAX_PS_TestDataFactory.CreateQuoteLines(serviceQuote,serviceQuoteIPLine,'1003',productSecond);
        qlList.add(quoteLine1);
        qlList.add(quoteLine2);
        qlList.add(quoteLine3);
        insert qlList; 
          for(SMAX_PS_Quote_Lines__c ql:qlList){
              ql.SMAX_PS_Refer_PB__c=false;
              ql.SMAX_PS_Customer_Procured__c=true;
              //ql.SMAX_PS_Product__c=product.id;
          }
          update qlList;
          /*******coverage for method "UpdateQuoteLinePriceBeforeInsertUpdate" ends********/
          
          //Updating pricebooks in quote for method "UpdateQuoteLinePriceAfterUpdate"
          serviceQuote.SMAX_PS_Parts_Price_Book__c=pricebookSecond.id;
          serviceQuote.SMAX_PS_Service_Pricebook__c=spbookSecond.id;
          update serviceQuote;
          /********Coverage for method "UpdateQuoteLinePriceBeforeInsertUpdate" ends****/
          
          //Creating a cloned serviceQuoteIpLine for the method "CreateQuoteLinesForClonedQuote"
          SMAX_PS_Service_Quote_IP_Line__c clonedServiceQuoteIPLine = SMAX_PS_TestDataFactory.CreateServiceQuoteIpLines(serviceQuote,null);
          clonedServiceQuoteIPLine.SMAX_PS_ClonedFromServiceQuoteIPLine__c =serviceQuoteIPLine.id;
          insert clonedServiceQuoteIPLine;
          /*****Coverage for the method "CreateQuoteLinesForClonedQuote" ends****/
          
    }
    
    
        
    
}