sgd/reproduction/playground/objects/SMAX_PS_Quote_Lines__c.object
<CustomObject>
    <fields>
        <fullName>SMAX_PS_Activity_Type__c</fullName>
        <label>アクティビティタイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Activity_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>アクティビティ</label>
        <referenceTo>SVMXC__Activity_Master__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Item_Name__c</fullName>
        <label>見積品目名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Line_Type__c</fullName>
        <label>種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <label>人件費</label>
                </value>
                <value>
                    <fullName>1002</fullName>
                    <label>検査機器</label>
                </value>
                <value>
                    <fullName>1003</fullName>
                    <label>部品明細</label>
                </value>
                <value>
                    <fullName>1004</fullName>
                    <label>その他</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Pack_Unit_No__c</fullName>
        <label>袋単位</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Remarks__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_SAP_HTSPlantStatus__c</fullName>
        <label>HTSプラントステータス</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_SAP_HTSPlantStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Quote_IP_Line__c</fullName>
        <label>見積対象製品・項番</label>
        <referenceTo>SMAX_PS_Service_Quote_IP_Line__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Unit_Of_Measure__c</fullName>
        <label>単位</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Unit_Of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Use_Purpose__c</fullName>
        <label>用途</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>見積明細</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SMAX_PS_Service_Quote_IP_Line__c.object
<CustomObject>
    <fields>
        <fullName>SMAX_PS_Service_Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>その他価格表</label>
        <referenceTo>SVMXC__Service_Pricebook__c</referenceTo>
        <relationshipLabel>Service Quote IP Line</relationshipLabel>
        <relationshipName>Service_Quote_IP_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Quote__c</fullName>
        <label>サービス見積</label>
        <referenceTo>SVMXC__Quote__c</referenceTo>
        <relationshipLabel>Service Quote IP Line</relationshipLabel>
        <relationshipName>Service_Quote_IP_Line</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Task_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>参照タスクテンプレート</label>
        <referenceTo>SVMXC__Task_Template__c</referenceTo>
        <relationshipLabel>Service Quote IP Line</relationshipLabel>
        <relationshipName>Service_Quote_IP_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>見積対象製品・項番</label>
    <nameField>
        <displayFormat>SIP-{0000000}</displayFormat>
        <label>Service Quote IP Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Activity_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Attach Activity Products Activity Product Level for the Activity Master.</description>
    <fields>
        <fullName>SMAX_PS_Unit_Of_Measure__c</fullName>
        <formula>CASE( SVMXC__Product__r.SMAX_PS_Unit_Of_Measure__c , 
&quot;Day&quot;, &quot;日&quot;,
&quot;Hour&quot;, &quot;時間&quot;,
&quot;Set&quot;, &quot;式&quot;,
&quot;Cycle&quot;, &quot;回&quot;,
&quot;Count&quot;, &quot;本&quot;,
&quot;Stay&quot;, &quot;泊&quot;,
&quot;ManDay&quot;, &quot;人&quot;,
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>単位（サービス品目）</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Activity_Product__c</fullName>
        <formula>TEXT(SVMXC__Activity__r.SVMXC__Activity_Type__c)+ &quot; : &quot; +
IF(LEN(SVMXC__Product__r.Id) &gt; 0,SVMXC__Product__r.Name,
IF(LEN(TEXT( SVMXC__Product_Line__c )) &gt; 0,TEXT(SVMXC__Product_Line__c),
IF(LEN(TEXT( SVMXC__Product_Family__c )) &gt; 0,TEXT(SVMXC__Product_Family__c),&apos;&apos;
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Activity Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Activity__c</fullName>
        <label>Activity</label>
        <referenceTo>SVMXC__Activity_Master__c</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Quote__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>In ServiceMax, Quote contains the estimated cost of a service event to be presented to a customer to get approval. A quote can be either created manually or generated automatically from the estimate lines of a service order.</description>
    <fields>
        <fullName>SMAX_PS_Parts_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>部品価格表</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Service_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Remarks__c</fullName>
        <label>備考</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Service_Pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>サービス価格表</label>
        <referenceTo>SVMXC__Service_Pricebook__c</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Service_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Quote</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Required_Part__c.object
<CustomObject>
    <description>Parts used to perform task</description>
    <fields>
        <fullName>SMAX_PS_Activity_Type__c</fullName>
        <label>アクティビティタイプ</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Activity_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>SVMXC__Activity_Master__c</referenceTo>
        <relationshipLabel>Required Parts</relationshipLabel>
        <relationshipName>Required_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Item_Name__c</fullName>
        <label>見積品目名</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Line_Type__c</fullName>
        <label>種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <label>人件費</label>
                </value>
                <value>
                    <fullName>1002</fullName>
                    <label>検査機器</label>
                </value>
                <value>
                    <fullName>1003</fullName>
                    <label>部品明細</label>
                </value>
                <value>
                    <fullName>1004</fullName>
                    <label>その他</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Pack_Unit_No__c</fullName>
        <label>袋単位</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Remarks__c</fullName>
        <label>備考</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_SAP_HTSPlantStatus__c</fullName>
        <formula>TEXT( SVMXC__Product__r.SMAX_PS_SAP_HTSPlantStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HTSプラントステータス（商品）</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMAX_PS_Unit_Of_Measure__c</fullName>
        <label>単位</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SMAX_PS_Unit_Of_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMAX_PS_Use_Purpose__c</fullName>
        <label>用途</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Required Parts</relationshipLabel>
        <relationshipName>Required_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SVMXC__Work_Order_Purpose__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order Purpose</label>
        <referenceTo>SVMXC__Task_Template__c</referenceTo>
        <relationshipLabel>Required Parts</relationshipLabel>
        <relationshipName>Required_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Required Part</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Service_Pricebook_Entry__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Represent price entry for service</description>
    <fields>
        <fullName>SMAX_PS_Unit_Of_Measure__c</fullName>
        <formula>SVMXC__Activity_Product__r.SMAX_PS_Unit_Of_Measure__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>単位（サービス品目）</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Activity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Product</label>
        <referenceTo>SVMXC__Activity_Product__c</referenceTo>
        <relationshipLabel>Service Pricebook Entry</relationshipLabel>
        <relationshipName>Service_Pricebook_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Activity_Type__c</fullName>
        <formula>IF( NOT(ISBLANK(SVMXC__Activity_Product__c)) , TEXT( SVMXC__Activity_Product__r.SVMXC__Activity__r.SVMXC__Activity_Type__c ),  IF( NOT(ISBLANK(SVMXC__Activity__c)) , TEXT(SVMXC__Activity__r.SVMXC__Activity_Type__c), &apos;&apos; )  )</formula>
        <label>Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Id</label>
        <referenceTo>SVMXC__Activity_Master__c</referenceTo>
        <relationshipLabel>Service Pricebook Entry (Activity)</relationshipLabel>
        <relationshipName>Service_Pricebook_Entry1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Price_Book__c</fullName>
        <label>Price Book</label>
        <referenceTo>SVMXC__Service_Pricebook__c</referenceTo>
        <relationshipLabel>Service Pricebook Entry</relationshipLabel>
        <relationshipName>PriceBook</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <formula>SVMXC__Activity_Product__r.SVMXC__Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Regular_Rate__c</fullName>
        <description>Regular Rate</description>
        <label>Regular Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Service Pricebook Entry</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Pricebook Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sgd/reproduction/playground/globalValueSets/SMAX_PS_Activity_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>3000</fullName>
        <label>作業費</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>検査機器</label>
    </customValue>
    <customValue>
        <fullName>5000</fullName>
        <label>その他</label>
    </customValue>
    <masterLabel>Activity Type</masterLabel>
</GlobalValueSet>

sgd/reproduction/playground/globalValueSets/SMAX_PS_SAP_HTSPlantStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Y0</fullName>
        <label>New/ prohibit Purc.Prod.</label>
    </customValue>
    <customValue>
        <fullName>Y1</fullName>
        <label>Technical change WIP</label>
    </customValue>
    <customValue>
        <fullName>Y2</fullName>
        <label>Proc. stoppage</label>
    </customValue>
    <customValue>
        <fullName>Y3</fullName>
        <label>New/ Prod order HMFR</label>
    </customValue>
    <customValue>
        <fullName>Y4</fullName>
        <label>New/ Obsolete HMFR</label>
    </customValue>
    <customValue>
        <fullName>Y5</fullName>
        <label>Std price unknown/ no mvt</label>
    </customValue>
    <customValue>
        <fullName>Y6</fullName>
        <label>購買禁止（購入不可）</label>
    </customValue>
    <customValue>
        <fullName>YA</fullName>
        <label>Non RoHS compliant</label>
    </customValue>
    <customValue>
        <fullName>YW</fullName>
        <label>原価なし</label>
    </customValue>
    <customValue>
        <fullName>YX</fullName>
        <label>メンテナンス対象外</label>
    </customValue>
    <customValue>
        <fullName>YY</fullName>
        <label>判別不能(原価あり）</label>
    </customValue>
    <customValue>
        <fullName>YZ</fullName>
        <label>判別不能</label>
    </customValue>
    <customValue>
        <fullName>Z0</fullName>
        <label>【国内使用禁止】調達/倉庫に対しブロック中</label>
    </customValue>
    <customValue>
        <fullName>Z1</fullName>
        <label>新規登録（未リリース）</label>
    </customValue>
    <customValue>
        <fullName>Z2</fullName>
        <label>再見積必要（送り発生時）</label>
    </customValue>
    <customValue>
        <fullName>Z3</fullName>
        <label>生産中止警告（メーカー終息部品）</label>
    </customValue>
    <customValue>
        <fullName>Z5</fullName>
        <label>廃止</label>
    </customValue>
    <masterLabel>HTSプラントステータス</masterLabel>
</GlobalValueSet>

sgd/reproduction/playground/globalValueSets/SMAX_PS_Unit_Of_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Day</fullName>
        <label>日</label>
    </customValue>
    <customValue>
        <fullName>Hour</fullName>
        <label>時間</label>
    </customValue>
    <customValue>
        <fullName>Set</fullName>
        <label>式</label>
    </customValue>
    <customValue>
        <fullName>Cycle</fullName>
        <label>回</label>
    </customValue>
    <customValue>
        <fullName>Count</fullName>
        <label>本</label>
    </customValue>
    <customValue>
        <fullName>Stay</fullName>
        <label>泊</label>
    </customValue>
    <customValue>
        <fullName>ManDay</fullName>
        <label>人</label>
    </customValue>
    <masterLabel>単位</masterLabel>
</GlobalValueSet>

sgd/reproduction/playground/classes/SVMX_PS_ServiceQuotePricing.cls
/**
* @description       : This class will handle the Service Quote Price calculation
* @author            : Vishnu Chandrasekar (SpringFive)
* @group             : Servicemax PS
* @last modified on  : 04-22-2021
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
* Modifications Log 
* Ver   Date         Author                               Modification
* 1.0   10-22-2020   Vishnu Chandrasekar                   Initial Version
**/   
public class SVMX_PS_ServiceQuotePricing {
    
    public static boolean triggerfromQuote = true;
    public static boolean triggerfromQuoteLine = true;
    
    public static void CreateQuoteLine(set<Id> QuoteIPId )
    {

        system.debug('HI');
        List<SMAX_PS_Service_Quote_IP_Line__c> QuoteIPLine = [select id,SMAX_PS_Service_Quote__c,SMAX_PS_Service_Quote__r.SMAX_PS_Parts_Price_Book__c,SMAX_PS_Service_Quote__r.SMAX_PS_Service_Pricebook__c, SMAX_PS_Task_Template__c from SMAX_PS_Service_Quote_IP_Line__c where Id in :QuoteIPId];
        system.debug('QuoteIPLine' +QuoteIPLine);
        set<id> TTSetId = new set<id>();
        //map<id,id> QuoteIdPriceBookIdMap = new map<id,id>();
        //map<id,id> QuoteIdServicePriceBookIdMap = new map<id,id>();
        set<id> priceBookIdSet = new set<id>();
        set<id> servicePriceBookIdSet = new set<id>();
        map<id,SMAX_PS_Service_Quote_IP_Line__c> QuoteIPIdTTSetId = new map<id,SMAX_PS_Service_Quote_IP_Line__c>();
        system.debug('QuoteIPLine'+QuoteIPLine);
        for(SMAX_PS_Service_Quote_IP_Line__c qip : QuoteIPLine)
        {
            system.debug('insedie');
            TTSetId.add(qip.SMAX_PS_Task_Template__c);
            if(qip.SMAX_PS_Service_Quote__r.SMAX_PS_Parts_Price_Book__c != null )
                priceBookIdSet.add(qip.SMAX_PS_Service_Quote__r.SMAX_PS_Parts_Price_Book__c);
            if(qip.SMAX_PS_Service_Quote__r.SMAX_PS_Service_Pricebook__c != null)
                servicePriceBookIdSet.add(qip.SMAX_PS_Service_Quote__r.SMAX_PS_Service_Pricebook__c);
            QuoteIPIdTTSetId.put(qip.id,qip);
            system.debug('QuoteIPIdTTSetId'+QuoteIPIdTTSetId);
            
        }
        
        
        //map<id,PricebookEntry> PBEIdRecMap = new map<id,PricebookEntry>([SELECT Id,UnitPrice,Product2Id,Pricebook2Id FROM PricebookEntry where Pricebook2Id in :priceBookIdSet ]);
        //map<id,SVMXC__Service_Pricebook_Entry__c> SPBEIdRecMap = new map<id,SVMXC__Service_Pricebook_Entry__c>([SELECT Id,SVMXC__Regular_Rate__c,SVMXC__Price_Book__c,SVMXC__Activity__c,SVMXC__Activity_Product__c,SVMXC__Activity_Type__c FROM SVMXC__Service_Pricebook_Entry__c where SVMXC__Price_Book__c in :servicePriceBookIdSet]);
        
        map<id,List<SVMXC__Required_Part__c>> TaskTemplateIdRequiredPartIdMap = new map<id,List<SVMXC__Required_Part__c>>();
        set<id> PartIdSet = new set<id>();
        set<id> ActivityIdSet = new set<id>();
        for(SVMXC__Required_Part__c rl : [select id,SVMXC__Product__c,SVMXC__Work_Order_Purpose__c,SMAX_PS_Activity__c,SMAX_PS_Line_Type__c,SVMXC__Quantity__c, SMAX_PS_Item_Name__c, SMAX_PS_SAP_HTSPlantStatus__c, SMAX_PS_Pack_Unit_No__c, SMAX_PS_Remarks__c, SMAX_PS_Unit_Of_Measure__c, SMAX_PS_Use_Purpose__c, SMAX_PS_Activity_Type__c, SMAX_PS_Service_Target__c, SMAX_PS_Product_Classification__c  from SVMXC__Required_Part__c where SVMXC__Work_Order_Purpose__c in :TTSetId])
        {
            if(rl.SVMXC__Product__c != null)
                PartIdSet.add(rl.SVMXC__Product__c);
            if(rl.SMAX_PS_Activity__c != null)
                ActivityIdSet.add(rl.SMAX_PS_Activity__c);
            if(TaskTemplateIdRequiredPartIdMap.containsKey(rl.SVMXC__Work_Order_Purpose__c) && TaskTemplateIdRequiredPartIdMap.get(rl.SVMXC__Work_Order_Purpose__c) != null) {
                List<SVMXC__Required_Part__c> reqPartActivityList = TaskTemplateIdRequiredPartIdMap.get(rl.SVMXC__Work_Order_Purpose__c);
                reqPartActivityList.add(rl);
                TaskTemplateIdRequiredPartIdMap.put(rl.SVMXC__Work_Order_Purpose__c,reqPartActivityList); 
            }   
            else {
                TaskTemplateIdRequiredPartIdMap.put(rl.SVMXC__Work_Order_Purpose__c, new List<SVMXC__Required_Part__c> {rl});
            }
            
        }
        map<string,PricebookEntry> PricebookIdProductIdRecMap = new map<string,PricebookEntry>();
        map<string,SVMXC__Service_Pricebook_Entry__c> ServicePricebookIdActivityIdRecMap = new map<string,SVMXC__Service_Pricebook_Entry__c>();
        
        for(PricebookEntry pbe : [SELECT Id,UnitPrice,Product2Id,Pricebook2Id FROM PricebookEntry where Pricebook2Id in :priceBookIdSet AND Product2Id in :PartIdSet] )
        {
            PricebookIdProductIdRecMap.put(pbe.Pricebook2Id+'#'+pbe.Product2Id,pbe);
        }
        system.debug('PricebookIdProductIdRecMap' +PricebookIdProductIdRecMap);
        for(SVMXC__Service_Pricebook_Entry__c spbe : [SELECT Id,SVMXC__Regular_Rate__c,SVMXC__Price_Book__c,SVMXC__Activity_Product__c,SVMXC__Activity_Type__c,SVMXC__Activity_Product__r.SVMXC__Product__c FROM SVMXC__Service_Pricebook_Entry__c where SVMXC__Price_Book__c in :servicePriceBookIdSet] )
        {
            ServicePricebookIdActivityIdRecMap.put(spbe.SVMXC__Price_Book__c+'#'+spbe.SVMXC__Activity_Product__r.SVMXC__Product__c+'#'+spbe.SVMXC__Activity_Type__c,spbe);
        }
        
        list<SMAX_PS_Quote_Lines__c> QuoteLineTobeAddList = new list<SMAX_PS_Quote_Lines__c>();
        for(id QuoteIpLineId : QuoteIPIdTTSetId.keySet()){
            if((TaskTemplateIdRequiredPartIdMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Task_Template__c))!=null){
            
            list<SVMXC__Required_Part__c> ReqPartList = TaskTemplateIdRequiredPartIdMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Task_Template__c);
            system.debug('ReqPartList' +ReqPartList.size());
            for(SVMXC__Required_Part__c rp : ReqPartList)
            {
                SMAX_PS_Quote_Lines__c QLsObject = new SMAX_PS_Quote_Lines__c();
                QLsObject.SMAX_PS_Service_Quote_IP_Line__c = QuoteIpLineId;
                QLsObject.SMAX_PS_Quote__c  = QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Service_Quote__c;
                QLsObject.SMAX_PS_Product__c = rp.SVMXC__Product__c;
                if(rp.SMAX_PS_Line_Type__c == '1003' )
                {
                    if(PricebookIdProductIdRecMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Service_Quote__r.SMAX_PS_Parts_Price_Book__c+'#'+rp.SVMXC__Product__c) != null )
                        QLsObject.SMAX_PS_Unit_Price__c = PricebookIdProductIdRecMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Service_Quote__r.SMAX_PS_Parts_Price_Book__c+'#'+rp.SVMXC__Product__c).UnitPrice;
                        QLsObject.SMAX_PS_Customer_Procured__c = false;
                    
                }
                else{
                    //QLsObject.SMAX_PS_Activity__c  = rp.SMAX_PS_Activity__c; 
                    if(ServicePricebookIdActivityIdRecMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Service_Quote__r.SMAX_PS_Service_Pricebook__c+'#'+rp.SVMXC__Product__c+'#'+rp.SMAX_PS_Activity_Type__c) != null ){
                        QLsObject.SMAX_PS_Unit_Price__c = ServicePricebookIdActivityIdRecMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Service_Quote__r.SMAX_PS_Service_Pricebook__c+'#'+rp.SVMXC__Product__c+'#'+rp.SMAX_PS_Activity_Type__c).SVMXC__Regular_Rate__c;
                        QLsObject.SMAX_PS_Service_PBE__c = ServicePricebookIdActivityIdRecMap.get(QuoteIPIdTTSetId.get(QuoteIpLineId).SMAX_PS_Service_Quote__r.SMAX_PS_Service_Pricebook__c+'#'+rp.SVMXC__Product__c+'#'+rp.SMAX_PS_Activity_Type__c).Id;
                    }
                    QLsObject.SMAX_PS_Refer_PB__c = true; //Nagur: by default need to be true for all non-parts lines
                    QLsObject.SMAX_PS_Expense_Target__c = true; //Nagur: by default need to be true for all non-parts lines
                }
                QLsObject.SMAX_PS_Line_Type__c = rp.SMAX_PS_Line_Type__c;
                QLsObject.SMAX_PS_Quantity2__c = rp.SVMXC__Quantity__c;
                //Nagur Add
                QLsObject.SMAX_PS_Item_Name__c = rp.SMAX_PS_Item_Name__c;
                QLsObject.SMAX_PS_Pack_Unit_No__c = rp.SMAX_PS_Pack_Unit_No__c;
                QLsObject.SMAX_PS_Remarks__c = rp.SMAX_PS_Remarks__c;
                QLsObject.SMAX_PS_Unit_Of_Measure__c = rp.SMAX_PS_Unit_Of_Measure__c;
                QLsObject.SMAX_PS_Use_Purpose__c = rp.SMAX_PS_Use_Purpose__c;
                QLsObject.SMAX_PS_SAP_HTSPlantStatus__c= rp.SMAX_PS_SAP_HTSPlantStatus__c;
                QLsObject.SMAX_PS_Activity_Type__c= rp.SMAX_PS_Activity_Type__c;
                QLsObject.SMAX_PS_Service_Target__c= rp.SMAX_PS_Service_Target__c;
                QLsObject.SMAX_PS_Product_Classification__c= rp.SMAX_PS_Product_Classification__c;
                //Nagur Add
                /*if(QLsObject.SMAX_PS_Line_Type__c != '1003'){
                    QLsObject.SMAX_PS_Refer_PB__c = true;
                    QLsObject.SMAX_PS_Expense_Target__c = true;
                }else{
                    QLsObject.SMAX_PS_Customer_Procured__c = false;
                }*/
                QuoteLineTobeAddList.add(QLsObject);
                
            }
            }
            
        }
        system.debug('QuoteLineTobeAddList' + QuoteLineTobeAddList);
        system.debug('QuoteLineTobeAddList size' + QuoteLineTobeAddList.size());
        //checkTriggerCanRun();
        triggerfromQuote = false;
        if(QuoteLineTobeAddList.size() > 0 )
            insert QuoteLineTobeAddList;
    }
    
    public static void UpdateQuoteLinePriceBeforeInsertUpdate(list<SMAX_PS_Quote_Lines__c> quoteLinesList,map<id,SMAX_PS_Quote_Lines__c>oldMapQuoteLines,map<id,SMAX_PS_Quote_Lines__c>newMapQuoteLines)
    {
        triggerfromQuoteLine = false;
        set<id> priceBookIdSet = new set<id>();
        set<id> PartIdSet = new set<id>();
        set<id> servicePriceBookIdSet = new set<id>();
        set<id> servicePriceBookEntryIdSet = new set<id>();
        set<id> ActivityIdSet = new set<id>();
        set<id> quoteIdSet = new set<id>();
        system.debug('Old map is' +oldMapQuoteLines);
        for(SMAX_PS_Quote_Lines__c ql : quoteLinesList){

            PartIdSet.add(ql.SMAX_PS_Product__c);
            servicePriceBookEntryIdSet.add(ql.SMAX_PS_Service_PBE__c);
            ActivityIdSet.add(ql.SMAX_PS_Activity__c);
            quoteIdSet.add(ql.SMAX_PS_Quote__c);
            
        }
        map<id,id> quoteIdPriceBookIdMap = new map<id,id>();
        map<id,id> quoteIdServicePriceBookIdMap = new map<id,id>();
        for(SVMXC__Quote__c qo : [select id,SMAX_PS_Parts_Price_Book__c,SMAX_PS_Service_Pricebook__c from SVMXC__Quote__c where id in : quoteIdSet ])
        {
            priceBookIdSet.add(qo.SMAX_PS_Parts_Price_Book__c);
            quoteIdPriceBookIdMap.put(qo.id,qo.SMAX_PS_Parts_Price_Book__c);
            servicePriceBookIdSet.add(qo.SMAX_PS_Service_Pricebook__c);
            quoteIdServicePriceBookIdMap.put(qo.id,qo.SMAX_PS_Service_Pricebook__c);
        }
        map<string,PricebookEntry> PricebookIdProductIdRecMap = new map<string,PricebookEntry>();
        map<string,SVMXC__Service_Pricebook_Entry__c> ServicePricebookIdActivityIdRecMap = new map<string,SVMXC__Service_Pricebook_Entry__c>();
        map<string,SVMXC__Service_Pricebook_Entry__c> SPIdActivityIdRecMap = new map<string,SVMXC__Service_Pricebook_Entry__c>();
        
        for(PricebookEntry pbe : [SELECT Id,UnitPrice,Product2Id,Pricebook2Id FROM PricebookEntry where Pricebook2Id in :priceBookIdSet AND Product2Id in :PartIdSet] )
        {
            PricebookIdProductIdRecMap.put(pbe.Pricebook2Id+'#'+pbe.Product2Id,pbe);
        }
        system.debug('PricebookIdProductIdRecMap' +PricebookIdProductIdRecMap);
        system.debug('servicePriceBookIdSet' +servicePriceBookIdSet);
        system.debug('ActivityIdSet' +ActivityIdSet);
        system.debug('PartIdSet' +PartIdSet);
       
        
        string dynSOQL = 'SELECT Id,SVMXC__Regular_Rate__c,SVMXC__Price_Book__c,SVMXC__Activity_Product__c,SVMXC__Activity_Type__c,SVMXC__Activity_Product__r.SVMXC__Product__c FROM SVMXC__Service_Pricebook_Entry__c where';
        string whereclause = '(SVMXC__Price_Book__c in : servicePriceBookIdSet)';
        /*if(!servicePriceBookEntryIdSet.isempty())
            whereclause = whereclause+'OR (Id in :servicePriceBookEntryIdSet AND SVMXC__Product__c in :PartIdSet)';*/
        system.debug('Query' +dynSOQL+' ' +whereclause);
        List<SVMXC__Service_Pricebook_Entry__c> spbeList = database.query(dynSOQL+' ' +whereclause);
        system.debug('spbeList'+spbeList);
        for(SVMXC__Service_Pricebook_Entry__c spbe : spbeList)
        {
            ServicePricebookIdActivityIdRecMap.put(spbe.SVMXC__Price_Book__c+'#'+spbe.SVMXC__Activity_Product__r.SVMXC__Product__c+'#'+spbe.SVMXC__Activity_Type__c,spbe);
            SPIdActivityIdRecMap.put(spbe.Id+'#'+spbe.SVMXC__Activity_Product__r.SVMXC__Product__c+'#'+spbe.SVMXC__Activity_Type__c,spbe);
        }
        Id quotePriceBookId;
        Id quoteServicePriceBookId;
        system.debug('SPIdActivityIdRecMap'+SPIdActivityIdRecMap);
        system.debug('ServicePricebookIdActivityIdRecMap'+ServicePricebookIdActivityIdRecMap);
        //list<SMAX_PS_Quote_Lines__c> quoteLinesTobeUpdate = new list<SMAX_PS_Quote_Lines__c>();
        for(SMAX_PS_Quote_Lines__c qls : quoteLinesList)
        {
            quotePriceBookId = quoteIdPriceBookIdMap.get(qls.SMAX_PS_Quote__c);
            quoteServicePriceBookId = quoteIdServicePriceBookIdMap.get(qls.SMAX_PS_Quote__c);
            if(qls.SMAX_PS_Line_Type__c  == '1003')
            {
                //Nagur Added SMAX_PS_Customer_Procured__c criteria
                if(qls.SMAX_PS_Customer_Procured__c == true)
                    qls.SMAX_PS_Unit_Price__c = 0;
                else {
                    if(PricebookIdProductIdRecMap.get(quotePriceBookId+'#'+qls.SMAX_PS_Product__c) != null )
                        qls.SMAX_PS_Unit_Price__c = PricebookIdProductIdRecMap.get(quotePriceBookId+'#'+qls.SMAX_PS_Product__c).UnitPrice;
                    else
                        qls.SMAX_PS_Unit_Price__c = 0;
                }
                
            }
            else
            {
                
                system.debug('Key is'+quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c);
                system.debug('oldMapQuoteLines' +oldMapQuoteLines);
                //system.debug('The value is'+oldMapQuoteLines.get(qls.id).SMAX_PS_Service_PBE__c+ 'Other value is'+oldMapQuoteLines.get(qls.id).SMAX_PS_Activity__c);
                //Scenario User creates new record with SPEID and Activity Id to update the unit price
                if(ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c) != null && oldMapQuoteLines == null )
                {
                    system.debug('Scene 1');
                    qls.SMAX_PS_Unit_Price__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c).SVMXC__Regular_Rate__c;
                    //qls.SMAX_PS_Service_PBE__c = ServicePricebookIdActivityIdRecMap.get(qls.SMAX_PS_Service_PBE__c+'#'+qls.SMAX_PS_Activity__c).Id;
                }
                //Scenario User creates new record with Only Activity Id to update the unit price
                /*else if( qls.SMAX_PS_Service_PBE__c == null && ServicePricebookIdActivityIdRecMap.get( quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c) != null && oldMapQuoteLines == null ){
                    qls.SMAX_PS_Unit_Price__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c).SVMXC__Regular_Rate__c;
                    system.debug('Scene 2');
                    qls.SMAX_PS_Service_PBE__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c).Id;
                }
                
                //Scenario User Changes the Price book entry and Activity id manually to update the unit price 
                else if(SPIdActivityIdRecMap.get(qls.SMAX_PS_Service_PBE__c+'#'+qls.SMAX_PS_Product__c) != null && qls.SMAX_PS_Service_PBE__c != null && oldMapQuoteLines.get(qls.id).SMAX_PS_Product__c != qls.SMAX_PS_Product__c && oldMapQuoteLines.get(qls.id).SMAX_PS_Service_PBE__c != qls.SMAX_PS_Service_PBE__c){
                    qls.SMAX_PS_Unit_Price__c = SPIdActivityIdRecMap.get(qls.SMAX_PS_Service_PBE__c+'#'+qls.SMAX_PS_Product__c).SVMXC__Regular_Rate__c;
                    system.debug('Scene 3');
                    //qls.SMAX_PS_Service_PBE__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Activity__c).Id;
                }*/
                //Scenario User nullify the Price book entry and change the Activity id manually to update the unit price 
                //Since trigger this code will be executed only for required field changes, clearing product change filter as checkbox change also need to be captured.
                //else if(ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c) != null && oldMapQuoteLines.get(qls.id).SMAX_PS_Product__c != qls.SMAX_PS_Product__c){
                else if(ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c) != null && qls.SMAX_PS_Refer_PB__c == true){
                    qls.SMAX_PS_Unit_Price__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c).SVMXC__Regular_Rate__c;
                    system.debug('Scene 4');
                    qls.SMAX_PS_Service_PBE__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c).Id;
                }
                
                //else if(oldMapQuoteLines.get(qls.id).SMAX_PS_Activity__c != qls.SMAX_PS_Activity__c && qls.SMAX_PS_Service_PBE__c == null && ServicePricebookIdActivityIdRecMap.get( quoteServicePriceBookId+'#'+qls.SMAX_PS_Activity__c) != null ){
                
                else{
                    system.debug('Scene 5');
                    //Nagur If price information is not fetched no need to reset the price
                    //qls.SMAX_PS_Unit_Price__c = 0;
                    //qls.SMAX_PS_Service_PBE__c = null;
                }
            }
        }
    }
    public static void UpdateQuoteLinePriceAfterUpdate(list<SMAX_PS_Quote_Lines__c> quoteLinesList,map<id,svmxc__quote__c>oldMapQuote,map<id,svmxc__quote__c>newMapQuote ){
        set<id> priceBookIdSet = new set<id>();
        set<id> PartIdSet = new set<id>();
        set<id> servicePriceBookEntryIdSet = new set<id>();
        set<id> ActivityIdSet = new set<id>();
        set<id> quoteIdSet = new set<id>();
        for(SMAX_PS_Quote_Lines__c ql : quoteLinesList){
            //priceBookIdSet.add(ql.SMAX_PS_Quote__r.SMAX_PS_Parts_Price_Book__c);
            PartIdSet.add(ql.SMAX_PS_Product__c);
            //servicePriceBookEntryIdSet.add(ql.SMAX_PS_Service_PBE__c);
            ActivityIdSet.add(ql.SMAX_PS_Activity__c);
            quoteIdSet.add(ql.SMAX_PS_Quote__c);
            
        }
        map<id,id> quoteIdPriceBookIdMap = new map<id,id>();
        map<id,id> quoteIdServicePriceBookIdMap = new map<id,id>();
        for(SVMXC__Quote__c qo : [select id,SMAX_PS_Parts_Price_Book__c,SMAX_PS_Service_Pricebook__c from SVMXC__Quote__c where id in : quoteIdSet ])
        {
            priceBookIdSet.add(qo.SMAX_PS_Parts_Price_Book__c);
            servicePriceBookEntryIdSet.add(qo.SMAX_PS_Service_Pricebook__c);
            quoteIdPriceBookIdMap.put(qo.id,qo.SMAX_PS_Parts_Price_Book__c);
            quoteIdServicePriceBookIdMap.put(qo.id,qo.SMAX_PS_Service_Pricebook__c);
        }
        map<string,PricebookEntry> PricebookIdProductIdRecMap = new map<string,PricebookEntry>();
        map<string,SVMXC__Service_Pricebook_Entry__c> ServicePricebookIdActivityIdRecMap = new map<string,SVMXC__Service_Pricebook_Entry__c>();
        
        for(PricebookEntry pbe : [SELECT Id,UnitPrice,Product2Id,Pricebook2Id FROM PricebookEntry where Pricebook2Id in :priceBookIdSet AND Product2Id in :PartIdSet] )
        {
            PricebookIdProductIdRecMap.put(pbe.Pricebook2Id+'#'+pbe.Product2Id,pbe);
        }
        system.debug('PricebookIdProductIdRecMap' +PricebookIdProductIdRecMap);
        for(SVMXC__Service_Pricebook_Entry__c spbe : [SELECT Id,SVMXC__Regular_Rate__c,SVMXC__Price_Book__c,SVMXC__Activity_Product__c,SVMXC__Activity_Type__c,SVMXC__Activity_Product__r.SVMXC__Product__c FROM SVMXC__Service_Pricebook_Entry__c where SVMXC__Price_Book__c in :servicePriceBookEntryIdSet] )
        {
            ServicePricebookIdActivityIdRecMap.put(spbe.SVMXC__Price_Book__c+'#'+spbe.SVMXC__Activity_Product__r.SVMXC__Product__c+'#'+spbe.SVMXC__Activity_Type__c,spbe);
        }
        Id quotePriceBookId;
        Id quoteServicePriceBookId;
        list<SMAX_PS_Quote_Lines__c> quoteLinesTobeUpdate = new list<SMAX_PS_Quote_Lines__c>();
        for(SMAX_PS_Quote_Lines__c qls : quoteLinesList)
        {
            quotePriceBookId = quoteIdPriceBookIdMap.get(qls.SMAX_PS_Quote__c);
            quoteServicePriceBookId = quoteIdServicePriceBookIdMap.get(qls.SMAX_PS_Quote__c);
            
            if(qls.SMAX_PS_Line_Type__c  == '1003' && (oldMapQuote.get(qls.SMAX_PS_Quote__c).SMAX_PS_Parts_Price_Book__c != newMapQuote.get(qls.SMAX_PS_Quote__c).SMAX_PS_Parts_Price_Book__c ) )
            {
                //Nagur Added SMAX_PS_Customer_Procured__c criteria
                if(qls.SMAX_PS_Customer_Procured__c == true)
                    qls.SMAX_PS_Unit_Price__c = 0;
                else {
                    if(PricebookIdProductIdRecMap.get(quotePriceBookId+'#'+qls.SMAX_PS_Product__c) != null )
                        qls.SMAX_PS_Unit_Price__c = PricebookIdProductIdRecMap.get(quotePriceBookId+'#'+qls.SMAX_PS_Product__c).UnitPrice;
                    else
                        qls.SMAX_PS_Unit_Price__c = 0;
                }                    
            }
            
            if(qls.SMAX_PS_Line_Type__c  != '1003' && oldMapQuote.get(qls.SMAX_PS_Quote__c).SMAX_PS_Service_Pricebook__c != newMapQuote.get(qls.SMAX_PS_Quote__c).SMAX_PS_Service_Pricebook__c)
            {
                system.debug('Inside Service Price');
                if(ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c) != null ){
                    system.debug('Update Service Prioce');
                    system.debug('Flat Rate is' +ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c).SVMXC__Regular_Rate__c);
                    qls.SMAX_PS_Unit_Price__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c).SVMXC__Regular_Rate__c;
                    qls.SMAX_PS_Service_PBE__c = ServicePricebookIdActivityIdRecMap.get(quoteServicePriceBookId+'#'+qls.SMAX_PS_Product__c+'#'+qls.SMAX_PS_Activity_Type__c).Id;
                }
                
                else{
                    
                    qls.SMAX_PS_Unit_Price__c = 0;
                    qls.SMAX_PS_Service_PBE__c = null;
                }
                
            }
            
            
            quoteLinesTobeUpdate.add(qls);
        }
        system.debug('quoteLinesTobeUpdate' +quoteLinesTobeUpdate);
        system.debug('triggerfromQuote' +triggerfromQuote);
        //checkTriggerCanRun();
        triggerfromQuote = false;
        update quoteLinesTobeUpdate;
        
    }
    
    public static boolean checkTriggerCanRun(){
    if(triggerfromQuote){
     triggerfromQuote=false;
     return true;
    }else{
        return triggerfromQuote;
    }
    }
    public static void CreateQuoteLinesForClonedQuote(Map<id,id> oldquoteipIdNewquoteipIdMap,Map<id,id> newquoteIPIdQuoteIdMap,set<id> oldquoteLineIdset){
        List<SMAX_PS_Quote_Lines__c> oldQuoteLineList = [SELECT SMAX_PS_Refer_PB__c,SMAX_PS_Service_Quote_IP_Line__c,SMAX_PS_Service_Target__c,SMAX_PS_Product_Classification__c,SMAX_PS_Service_PBE__c,SMAX_PS_Item_Name__c,SMAX_PS_Quantity2__c,SMAX_PS_Unit_Price__c,SMAX_PS_Expense_Target__c,
                                                        SMAX_PS_Activity__c,SMAX_PS_Product__c,SMAX_PS_Line_Type__c,SMAX_PS_Customer_Procured__c,SMAX_PS_Use_Purpose__c,SMAX_PS_Remarks__c,SMAX_PS_SAP_HTSPlantStatus__c,SMAX_PS_Pack_Unit_No__c FROM SMAX_PS_Quote_Lines__c WHERE SMAX_PS_Service_Quote_IP_Line__c in :oldquoteLineIdset];
        system.debug('oldQuoteLineList'+oldQuoteLineList.size());

        List<SMAX_PS_Quote_Lines__c> QuoteLineTobeInserted=new List<SMAX_PS_Quote_Lines__c>();
        for(SMAX_PS_Quote_Lines__c oldqls:oldQuoteLineList){
            //id oldsqIpLineId=oldqls.SMAX_PS_Service_Quote_IP_Line__c;
            SMAX_PS_Quote_Lines__c clonedquoteLines = oldqls.clone(false);
            system.debug(oldquoteipIdNewquoteipIdMap.get(oldqls.SMAX_PS_Service_Quote_IP_Line__c));
            system.debug(newquoteIPIdQuoteIdMap.get(oldquoteipIdNewquoteipIdMap.get(oldqls.SMAX_PS_Service_Quote_IP_Line__c)));
            clonedquoteLines.SMAX_PS_Service_Quote_IP_Line__c=oldquoteipIdNewquoteipIdMap.get(oldqls.SMAX_PS_Service_Quote_IP_Line__c);
            clonedquoteLines.SMAX_PS_Quote__c = newquoteIPIdQuoteIdMap.get(oldquoteipIdNewquoteipIdMap.get(oldqls.SMAX_PS_Service_Quote_IP_Line__c));
            clonedquoteLines.SMAX_PS_Cloned_From_Quote_Lines__c = oldqls.id; 
            QuoteLineTobeInserted.add(clonedquoteLines);
            
        }
        system.debug('QuoteLineTobeInserted' + QuoteLineTobeInserted);
        if(QuoteLineTobeInserted.size()>0)
            insert QuoteLineTobeInserted;


    }
    /*public static void CreateQuoteLinesForClonedQuote(Map<id,id> clonedFromIdQuoteIpLineMap,Map<id,id> quoteIpLineIdQuoteIdMap,set<id> oldquoteLineIdset){
        set<id> clonedFromIdSet=clonedFromIdQuoteIpLineMap.keyset();

        List<SMAX_PS_Quote_Lines__c> QuoteLineList = [SELECT id,Name,SMAX_PS_Refer_PB__c,SMAX_PS_Service_Quote_IP_Line__c,SMAX_PS_Service_Target__c,SMAX_PS_Product_Classification__c,SMAX_PS_Service_PBE__c,SMAX_PS_Item_Name__c,SMAX_PS_Quantity2__c,SMAX_PS_Pack_Unit_No__c,SMAX_PS_Unit_Price__c,SMAX_PS_Expense_Target__c,
                                                        SMAX_PS_Activity__c,SMAX_PS_Product__c,SMAX_PS_Line_Type__c,SMAX_PS_Customer_Procured__c,SMAX_PS_Use_Purpose__c,SMAX_PS_Remarks__c,SMAX_PS_SAP_HTSPlantStatus__c
                                                        FROM SMAX_PS_Quote_Lines__c WHERE SMAX_PS_Service_Quote_IP_Line__c IN : clonedFromIdSet];
        //List<SMAX_PS_Quote_Lines__c> newQuoteLineList = QuoteLineList;
        List<SMAX_PS_Quote_Lines__c> clonedQlList = new List<SMAX_PS_Quote_Lines__c>();
        for(SMAX_PS_Quote_Lines__c qlInstance:QuoteLineList){
            id oldsqIpLineId=qlInstance.SMAX_PS_Service_Quote_IP_Line__c;
            qlInstance.SMAX_PS_Service_Quote_IP_Line__c=clonedFromIdQuoteIpLineMap.get(oldsqIpLineId);
            qlInstance.SMAX_PS_Quote__c = quoteIpLineIdQuoteIdMap.get(qlInstance.SMAX_PS_Service_Quote_IP_Line__c);
            qlInstance.id=null;
            clonedQlList.add(qlInstance);
        }
        //List<SMAX_PS_Quote_Lines__c> clonedQlList = new List<SMAX_PS_Quote_Lines__c>(QuoteLineList);
        //DML
        Insert clonedQlList;


    }*/
    
}