sgd/reproduction/playground/objects/SVMXC__Installed_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <fields>
        <fullName>SVMXC__City__c</fullName>
        <description>“City” part of the physical location address</description>
        <inlineHelpText>“City” part of the physical location address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
        <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N70000001hzZ0EAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Country__c</fullName>
        <description>“Country” part of the physical location address</description>
        <inlineHelpText>“Country” part of the physical location address</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Ayerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas, The</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bouvet Is</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>British Indian Ocean Territory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__State__c</fullName>
        <description>“State/Province” part of the physical location address</description>
        <inlineHelpText>“State/Province” part of the physical location address</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Street__c</fullName>
        <description>“Street” part of the physical location address</description>
        <inlineHelpText>“Street” part of the physical location address</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SVMXC__Zip__c</fullName>
        <description>“Zip/Postal Code” part of the physical location address</description>
        <inlineHelpText>“Zip/Postal Code” part of the physical location address</inlineHelpText>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/objects/SVMXC__Service_Order__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <fields>
        <fullName>SMAX_PS_Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Installed Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__City__c</fullName>
        <description>“City” part of the work order location.</description>
        <inlineHelpText>“City” part of the work order location.</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
        <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Service_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
        <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
        <label>Component</label>
        <referenceTo>SVMXC__Installed_Product__c</referenceTo>
        <relationshipName>Service_Order_Component</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Country__c</fullName>
        <description>“Country” part of the work order location</description>
        <inlineHelpText>“Country” part of the work order location</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bouvet</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>British Indian Ocean Territory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__State__c</fullName>
        <description>“State” part of the work order location</description>
        <inlineHelpText>“State” part of the work order location</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Street__c</fullName>
        <description>“Street” part of the work order location</description>
        <inlineHelpText>“Street” part of the work order location</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SVMXC__Zip__c</fullName>
        <description>“Zip code” part of the work order location</description>
        <inlineHelpText>“Zip code” part of the work order location</inlineHelpText>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sgd/reproduction/playground/classes/SMAX_PS_SetAddressOnWOWebServ.cls
/**
* @CLASS: SMAX_PS_SetAddressOnWOWebServ
*
* @DESCRIPTION: This class is used to set the address fields on a work order based on the address type selected. The current choices for address type
                are Account and Installed Product. The fields on work order copy the addresses from these 2 related parent records
*
*-------------------------------------------------------------------------------------------------------------------
* DEVELOPER                     DATE                  REASON
*-------------------------------------------------------------------------------------------------------------------
* ServiceMax/Shreyas         2021-03-03              Created
********************************************************************************************************************/
global class SMAX_PS_SetAddressOnWOWebServ
{
    webservice static SVMXC.SFM_WrapperDef.SFM_PageData setAddress(SVMXC.SFM_WrapperDef.SFM_TargetRecord request)
    {
        SVMXC.SFM_WrapperDef.SFM_PageData pagedata = new SVMXC.SFM_WrapperDef.SFM_PageData();
        SVMXC.SFM_ServicesDef def = new SVMXC.SFM_ServicesDef();
        Map<String,Schema.SObjectType> mapAllobj = new Map<String, Schema.SObjectType>();
        Map<String, Schema.SObjectType> mapGlobalDesc = new Map<String, Schema.SObjectType>();
        Map<String,List<Sobject>> detailSobjectMap = new Map<String, List<Sobject>>();

        mapGlobalDesc = Schema.getGlobalDescribe();

        if(mapGlobalDesc.size() > 0)
        {
            for(Schema.SObjectType schIterator : mapGlobalDesc.values())
            {
                Schema.DescribeSObjectResult result = schIterator.getDescribe();
                mapAllobj.put(result.getName(), schIterator);
            }
        }

        Sobject headerSobj = def.SFM_Page_GetHeaderRecord(request, mapAllobj);
        SVMXC__Service_Order__c objWO = new SVMXC__Service_Order__c();
        objWO = (SVMXC__Service_Order__c)headerSobj;

        if(objWO.SMAX_PS_Address_Type__c != null)
        {
            if(objWO.SMAX_PS_Address_Type__c == 'Account')
            {
                for(Account accIterator : [Select Id, BillingStreet, BillingState, BillingPostalCode, BillingCountry, BillingCity From Account
                                           Where Id =: objWO.SVMXC__Company__c Limit 1])
                {
                    objWO.SVMXC__Street__c = accIterator.BillingStreet;
                    objWO.SVMXC__State__c = accIterator.BillingState;
                    objWO.SVMXC__Zip__c = accIterator.BillingPostalCode;
                    objWO.SVMXC__Country__c = accIterator.BillingCountry;
                    objWO.SVMXC__City__c = accIterator.BillingCity;
                }
            }
            else if(objWO.SMAX_PS_Address_Type__c == 'Installed Product')
            {
                for(SVMXC__Installed_Product__c ipIterator : [Select Id, SVMXC__Street__c, SVMXC__State__c, SVMXC__Zip__c, SVMXC__Country__c, SVMXC__City__c
                                                              From SVMXC__Installed_Product__c Where Id =: objWO.SVMXC__Component__c Limit 1])
                {
                    objWO.SVMXC__Street__c = ipIterator.SVMXC__Street__c;
                    objWO.SVMXC__State__c = ipIterator.SVMXC__State__c;
                    objWO.SVMXC__Zip__c = ipIterator.SVMXC__Zip__c;
                    objWO.SVMXC__Country__c = ipIterator.SVMXC__Country__c;
                    objWO.SVMXC__City__c = ipIterator.SVMXC__City__c;
                }
            }
            try
            {
                Update objWO;
                pagedata.response.message = 'Saved Successfully'; 
                pagedata.response.success = true; 
                pagedata.response.messageType = 'SVMX_SUCCESS';
            }
            catch(Exception ex)
            {
                pagedata .response.message = ex.getmessage(); 
                pagedata.response.success = false; 
                pagedata.response.messageType = 'SVMX_ERROR'; 
                return pagedata;
            }
        }
        detailSobjectMap = def.SFM_Page_GetDetailRecords(request, mapAllobj);
        pagedata = def.SFM_Page_BuildResponse(request, objWO, detailSobjectMap); 
        system.debug('Response = ' + pagedata); 
        return pagedata;
    }
}